language: c

compiler:
- clang
- gcc

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y indent valgrind

script:
- bin/fetch-configlet
- bin/configlet lint .
- bin/verify-indent
- shellcheck bin/*
- bin/run-tests
